blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question
    url: https://github.com/mohit-tanwar-dev/python-backend/discussions
    about: Ask questions and discuss ideas in Discussions.
